project_name: kafkamirror
release:
  github:
    owner: tufitko
    name: kafkamirror

builds:
  - id: kafkamirror
    binary: kafkamirror
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - kafkamirror
    image_templates:
      - "tufitko/kafkamirror:v{{ .Version }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
    use: buildx
  - goos: linux
    goarch: arm64
    ids:
      - kafkamirror
    image_templates:
      - "tufitko/kafkamirror:v{{ .Version }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
    use: buildx
docker_manifests:
  - name_template: tufitko/kafkamirror:v{{ .Version }}
    image_templates:
      - tufitko/kafkamirror:v{{ .Version }}-amd64
      - tufitko/kafkamirror:v{{ .Version }}-arm64
